project_id = "wncskhubrkivfcgigemz"

[functions.eve-auth]
verify_jwt = false

[functions.discord-auth]
verify_jwt = false

[functions.cleanup-users]
verify_jwt = false

[functions.refresh-character]
verify_jwt = false

[functions.sync-eve-roles]
verify_jwt = false

[functions.manage-roles]
verify_jwt = true
